# Generated by Django 5.0.6 on 2024-10-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("comision", models.CharField(max_length=20)),
                ("Profesor", models.CharField(max_length=50)),
                ("Descripcion", models.TextField(max_length=200)),
                ("cupo", models.IntegerField(default=0)),
                (
                    "precio",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True, null=True, upload_to="producto/%Y/%m/%d"
                    ),
                ),
                ("direccion", models.CharField(max_length=200)),
            ],
        ),
    ]
