# Generated by Django 5.0.6 on 2024-11-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cursos", "0002_ticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="Descripcion",
            field=models.TextField(max_length=500),
        ),
    ]
