# Generated by Django 5.0.6 on 2024-10-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usuario", models.CharField(max_length=150, null=True)),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        default="defecto/defecto.png",
                        null=True,
                        upload_to="producto/%Y/%m/%d",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("apellido", models.CharField(max_length=50)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("pais", models.CharField(blank=True, max_length=30)),
                ("provincia", models.CharField(blank=True, max_length=40)),
                ("ciudad", models.CharField(blank=True, max_length=40)),
                ("domicilio", models.CharField(blank=True, max_length=80)),
                ("codigo_postal", models.CharField(blank=True, max_length=50)),
                ("telefono", models.CharField(blank=True, max_length=30)),
                ("celular", models.CharField(blank=True, max_length=30)),
                ("documento", models.CharField(blank=True, max_length=30)),
                ("cuit", models.CharField(blank=True, max_length=30)),
                ("Graduacion", models.CharField(max_length=200)),
            ],
        ),
    ]
