# Generated by Django 5.0.6 on 2024-11-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
    ]
