# Generated by Django 5.0.6 on 2024-11-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academia", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Noticia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        choices=[
                            ("gimnasio", "Nuevo Gimnasio"),
                            ("cursos", "Cursos de Primeros Auxilios"),
                            ("heridas", "Heridas Deportivas"),
                            ("examenes", "Exámenes para Cinturones"),
                            ("profesores", "Novedades de Profesores"),
                        ],
                        max_length=255,
                    ),
                ),
                ("contenido", models.TextField()),
                ("fecha_publicacion", models.DateTimeField(auto_now_add=True)),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="noticias/"),
                ),
            ],
        ),
    ]
