# Generated by Django 5.0.6 on 2024-11-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academia", "0002_noticia"),
    ]

    operations = [
        migrations.AddField(
            model_name="noticia",
            name="mostrar",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="noticia",
            name="titulo",
            field=models.CharField(max_length=255),
        ),
    ]
